-- 테이블 생성
CREATE TABLE PRACTICE_MEMO(
	MEMO_NO NUMBER,
	MEMO_TITLE VARCHAR2(200),
	MEMO_CONTENT VARCHAR2(4000),
	REG_DATE DATE DEFAULT SYSDATE
);

-- 제약조건 추가
ALTER TABLE PRACTICE_MEMO 
ADD CONSTRAINT MEMO_PK PRIMARY KEY(MEMO_NO);

ALTER TABLE PRACTICE_MEMO 
ADD CONSTRAINT MEMO_UK UNIQUE(MEMO_TITLE);

COMMENT ON COLUMN PRACTICE_MEMO.MEMO_NO IS '메모 번호';
COMMENT ON COLUMN PRACTICE_MEMO.MEMO_TITLE IS '메모 제목';
COMMENT ON COLUMN PRACTICE_MEMO.MEMO_CONTENT IS '메모 내용';
COMMENT ON COLUMN PRACTICE_MEMO.REG_DATE IS '작성일';

-- 시퀀스 생성
CREATE SEQUENCE SEQ_MEMO_NO NOCACHE;

-- 샘플 데이터
INSERT INTO PRACTICE_MEMO
VALUES(SEQ_MEMO_NO.NEXTVAL, '테스트1', '테스트1 입니다.', DEFAULT);

INSERT INTO PRACTICE_MEMO
VALUES(SEQ_MEMO_NO.NEXTVAL, '테스트2', '테스트2 입니다.', DEFAULT);

INSERT INTO PRACTICE_MEMO
VALUES(SEQ_MEMO_NO.NEXTVAL, '테스트3', '테스트3 입니다.', DEFAULT);

COMMIT;

SELECT * FROM PRACTICE_MEMO;

